// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7766",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "hexagonal-arch",
	Description:      "API Documentation for hexagonal-arch",
	InfoInstanceName: "swagger",
	//SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
